openapi: 3.1.0
info:
  title: Company RAG Backend
  version: 1.0.0
servers:
  - url: https://candelaria-periphrastic-deformedly.ngrok-free.dev
paths:
  /chat:
    post:
      operationId: ragChat
      summary: Answer questions using company documents (RAG)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                query:
                  type: string
                  description: The user's question
                top_k:
                  type: integer
                  minimum: 1
                  maximum: 20
                  default: 5
                  description: Number of chunks to retrieve
              required: [query]
      responses:
        "200":
          description: RAG answer and supporting evidence
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
                properties:
                  answer:
                    type: string
                  citations:
                    type: array
                    items:
                      type: object
                      additionalProperties: true
                      properties:
                        title:
                          type: string
                        section:
                          type: string
                        url:
                          type: string
                  results:
                    type: array
                    items:
                      type: object
                      additionalProperties: true
                      properties:
                        text:
                          type: string
                        title:
                          type: string
                        section:
                          type: string
                        url:
                          type: string
                        score:
                          type: number